## makefile automates the build and deployment for python projects

## build
# type of project
PROJ_TYPE=		python

# replace interpreter with virtualenv
#PYTHON_BIN =		$(PROJ_PYENV_DIR)/bin/python3

# current directory
PROJ_DIR=		$(abspath $(shell pwd))

# somewhat temporary directory (not present on clone)
DATA_DIR=		data

# where logs go
LOG_DIR=		log

# additional resources generated by the build that should be cleaned up
ADD_CLEAN +=		$(wildcard *.log) nohup.out
ADD_CLEAN_ALL +=	$(DATA_DIR)/proc results
ADD_CLEAN_VAPORIZE +=	$(PROJ_PYENV_DIR) $(DATA_DIR) $(LOG_DIR)

## project
# cli
APP_ARGS=		-c resources/dlqa.conf

# virtual environment
PROJ_PYENV_DIR =	$(PROJ_DIR)/pyinst

include ./zenbuild/main.mk

$(PROJ_PYENV_DIR):
		virtualenv $(PROJ_PYENV_DIR)

.PHONY:		virtualenv
virtualenv:	$(PROJ_PYENV_DIR) pydeps
		$(PYTHON_BIN) -m spacy download en_core_web_sm

$(LOG_DIR):
		mkdir -p $(LOG_DIR)

.PHONY:		parse
parse:		$(LOG_DIR)
		nohup make PYTHON_BIN_ARGS="$(APP_ARGS) parse" run > $(LOG_DIR)/parse.log 2>&1 &

.PHONY:		features
features:	$(LOG_DIR)
		nohup make PYTHON_BIN_ARGS="$(APP_ARGS) features" run > $(LOG_DIR)/features.log 2>&1 &

.PHONY:		train
train:		$(LOG_DIR)
		nohup make PYTHON_BIN_ARGS="$(APP_ARGS) train" run > $(LOG_DIR)/train.log 2>&1 &

.PHONY:		testmodel
testmodel:	$(LOG_DIR)
		nohup make PYTHON_BIN_ARGS="$(APP_ARGS) test" run > $(LOG_DIR)/test.log 2>&1 &

.PHONY:		traintest
traintest:	$(LOG_DIR)
		nohup make PYTHON_BIN_ARGS="$(APP_ARGS) traintest" run > $(LOG_DIR)/traintest.log 2>&1 &

.PHONY:		calcrank
calcrank:	$(LOG_DIR)
		nohup make PYTHON_BIN_ARGS="$(APP_ARGS) calcrank" run > $(LOG_DIR)/calcrank.log 2>&1 &

.PHONY:		calcmrr
calcmrr:	$(LOG_DIR)
		nohup make PYTHON_BIN_ARGS="$(APP_ARGS) calcmrr" run > $(LOG_DIR)/calcmrr.log 2>&1 &

.PHONY:		lsammr
lsammr:		$(LOG_DIR)
		nohup make PYTHON_BIN_ARGS="$(APP_ARGS) lsammr" run > $(LOG_DIR)/lsammr.log 2>&1 &

.PHONY:		cleanrank
cleanrank:
		rm -fr $(MTARG)/rank

.PHONY:		doall
doall:
		make PYTHON_BIN_ARGS="$(APP_ARGS) parse" run > $(LOG_DIR)/parse.log 2>&1
		make PYTHON_BIN_ARGS="$(APP_ARGS) features" run > $(LOG_DIR)/features.log 2>&1
		make PYTHON_BIN_ARGS="$(APP_ARGS) traintest" run > $(LOG_DIR)/traintest.log 2>&1
		make PYTHON_BIN_ARGS="$(APP_ARGS) calcrank" run > $(LOG_DIR)/calcrank.log 2>&1
		make PYTHON_BIN_ARGS="$(APP_ARGS) calcmrr" run > $(LOG_DIR)/calcmrr.log 2>&1
		make PYTHON_BIN_ARGS="$(APP_ARGS) lsammr" run > $(LOG_DIR)/lsammr.log 2>&1

.PHONY:		all
all:		virtualenv $(LOG_DIR)
		nohup make doall > $(LOG_DIR)/all.log 2>&1 &

.PHONY:		stop
stop:
		killall $(PYTHON_BIN)

.PHONY:		vaporize
vaporize:	cleanall
		rm -fr $(ADD_CLEAN_VAPORIZE)
